apiVersion: v1
kind: Pod
metadata:
  name: lustre-mount
  namespace: lustre
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - args:
    - /bin/cat
    stdin: true
    image: image-registry.openshift-image-registry.svc:5000/lustre/lustre:4.18.0
    name: lustre1
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - name: host-dev
      mountPath: /dev
    - name: host-sys
      mountPath: /sys
    - name: host
      mountPath: /host
      mountPropagation: Bidirectional
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  hostNetwork: true
  volumes:
  - name: host-dev
    hostPath:
      path: /dev
  - name: host-sys
    hostPath:
      path: /sys
  - name: host
    hostPath:
      path: /
