apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  audit:
    auditChunkSize: 66
    auditFromCache: Enabled
    auditInterval: 10s
    constraintViolationLimit: 55
    emitAuditEvents: Enabled
    logLevel: DEBUG
    replicas: 1
  mutatingWebhook: Enabled
  validatingWebhook: Enabled
  webhook:
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
        - key: admission.gatekeeper.sh/enabled
          operator: Exists
