apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: lustre-kmod
  name: lustre-kmod
  namespace: lustre-kmod
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: lustre-kmod-build
  name: lustre-kmod-build
  namespace: lustre-kmod
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
  source:
    git:
      ref: "main"
      uri: "https://github.com/kincl/lustre-kmod-container.git"
    type: Git
  strategy:
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: lustre-kmod:latest